name: FlightPriceTracker
options:
  bundleIdPrefix: com.flightpricetracker
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "14.0"
  createIntermediateGroups: true

settings:
  base:
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  FlightPriceTracker:
    type: application
    platform: macOS
    sources:
      - path: FlightPriceTracker
        excludes:
          - "*.entitlements"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.flightpricetracker.app
        INFOPLIST_FILE: FlightPriceTracker/Info.plist
        CODE_SIGN_ENTITLEMENTS: FlightPriceTracker/FlightPriceTracker.entitlements
        SWIFT_VERSION: "5.9"
    entitlements:
      path: FlightPriceTracker/FlightPriceTracker.entitlements
    dependencies:
      - target: FlightWidgetExtension
        embed: true
        codeSign: true

  FlightWidgetExtension:
    type: app-extension
    platform: macOS
    sources:
      - path: FlightWidget
        excludes:
          - "*.entitlements"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.flightpricetracker.app.widget
        INFOPLIST_FILE: FlightWidget/Info.plist
        CODE_SIGN_ENTITLEMENTS: FlightWidget/FlightWidgetExtension.entitlements
        SWIFT_VERSION: "5.9"
        SKIP_INSTALL: YES
    entitlements:
      path: FlightWidget/FlightWidgetExtension.entitlements

schemes:
  FlightPriceTracker:
    build:
      targets:
        FlightPriceTracker: all
        FlightWidgetExtension: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
